apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  name: pkmn
spec:
  selector: {}
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
    spec:
      containers:
      - env:
        - name: POC
          value: POC
        image: quay.io/redhat-appstudio-qe/byoc-yesq-tenant/byoc-app-kqkf/pkmn@sha256:f9c7df3a5c537f11ca76afeb94647a50bf7e1d20de2ffaaa3760d76e0f91da7a
        name: my-java-quarkus
        resources: {}
status: {}
