apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  creationTimestamp: null
  labels:
    app.kubernetes.io/created-by: application-service
    app.kubernetes.io/instance: pkmn
    app.kubernetes.io/managed-by: kustomize
    app.kubernetes.io/name: pkmn
    app.kubernetes.io/part-of: byoc-app-kqkf
  name: pkmn
spec:
  rules:
  - host: pkmn-byoc-yesq-tenant.apps.4194534b3cd466604581.hypershift.aws-2.ci.openshift.org
    http:
      paths:
      - backend:
          service:
            name: pkmn
            port:
              number: 8081
        path: /
        pathType: ImplementationSpecific
status:
  loadBalancer: {}
